//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace DataAccessLayer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class KCDC2012Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new KCDC2012Entities object using the connection string found in the 'KCDC2012Entities' section of the application configuration file.
        /// </summary>
        public KCDC2012Entities() : base("name=KCDC2012Entities", "KCDC2012Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new KCDC2012Entities object.
        /// </summary>
        public KCDC2012Entities(string connectionString) : base(connectionString, "KCDC2012Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new KCDC2012Entities object.
        /// </summary>
        public KCDC2012Entities(EntityConnection connection) : base(connection, "KCDC2012Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RegistrationFee> RegistrationFees
        {
            get
            {
                if ((_RegistrationFees == null))
                {
                    _RegistrationFees = base.CreateObjectSet<RegistrationFee>("RegistrationFees");
                }
                return _RegistrationFees;
            }
        }
        private ObjectSet<RegistrationFee> _RegistrationFees;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Speaker> Speakers
        {
            get
            {
                if ((_Speakers == null))
                {
                    _Speakers = base.CreateObjectSet<Speaker>("Speakers");
                }
                return _Speakers;
            }
        }
        private ObjectSet<Speaker> _Speakers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Technology> Technologies
        {
            get
            {
                if ((_Technologies == null))
                {
                    _Technologies = base.CreateObjectSet<Technology>("Technologies");
                }
                return _Technologies;
            }
        }
        private ObjectSet<Technology> _Technologies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Session> Sessions
        {
            get
            {
                if ((_Sessions == null))
                {
                    _Sessions = base.CreateObjectSet<Session>("Sessions");
                }
                return _Sessions;
            }
        }
        private ObjectSet<Session> _Sessions;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RegistrationFees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRegistrationFees(RegistrationFee registrationFee)
        {
            base.AddObject("RegistrationFees", registrationFee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Speakers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSpeakers(Speaker speaker)
        {
            base.AddObject("Speakers", speaker);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Technologies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTechnologies(Technology technology)
        {
            base.AddObject("Technologies", technology);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sessions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSessions(Session session)
        {
            base.AddObject("Sessions", session);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KCDC2012Model", Name="RegistrationFee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RegistrationFee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RegistrationFee object.
        /// </summary>
        /// <param name="registrationFeeID">Initial value of the RegistrationFeeID property.</param>
        /// <param name="minYearsExperience">Initial value of the MinYearsExperience property.</param>
        /// <param name="maxYearsExperience">Initial value of the MaxYearsExperience property.</param>
        /// <param name="fee">Initial value of the Fee property.</param>
        public static RegistrationFee CreateRegistrationFee(global::System.Int32 registrationFeeID, global::System.Int32 minYearsExperience, global::System.Int32 maxYearsExperience, global::System.Int32 fee)
        {
            RegistrationFee registrationFee = new RegistrationFee();
            registrationFee.RegistrationFeeID = registrationFeeID;
            registrationFee.MinYearsExperience = minYearsExperience;
            registrationFee.MaxYearsExperience = maxYearsExperience;
            registrationFee.Fee = fee;
            return registrationFee;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RegistrationFeeID
        {
            get
            {
                return _RegistrationFeeID;
            }
            set
            {
                if (_RegistrationFeeID != value)
                {
                    OnRegistrationFeeIDChanging(value);
                    ReportPropertyChanging("RegistrationFeeID");
                    _RegistrationFeeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RegistrationFeeID");
                    OnRegistrationFeeIDChanged();
                }
            }
        }
        private global::System.Int32 _RegistrationFeeID;
        partial void OnRegistrationFeeIDChanging(global::System.Int32 value);
        partial void OnRegistrationFeeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MinYearsExperience
        {
            get
            {
                return _MinYearsExperience;
            }
            set
            {
                OnMinYearsExperienceChanging(value);
                ReportPropertyChanging("MinYearsExperience");
                _MinYearsExperience = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinYearsExperience");
                OnMinYearsExperienceChanged();
            }
        }
        private global::System.Int32 _MinYearsExperience;
        partial void OnMinYearsExperienceChanging(global::System.Int32 value);
        partial void OnMinYearsExperienceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaxYearsExperience
        {
            get
            {
                return _MaxYearsExperience;
            }
            set
            {
                OnMaxYearsExperienceChanging(value);
                ReportPropertyChanging("MaxYearsExperience");
                _MaxYearsExperience = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxYearsExperience");
                OnMaxYearsExperienceChanged();
            }
        }
        private global::System.Int32 _MaxYearsExperience;
        partial void OnMaxYearsExperienceChanging(global::System.Int32 value);
        partial void OnMaxYearsExperienceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Fee
        {
            get
            {
                return _Fee;
            }
            set
            {
                OnFeeChanging(value);
                ReportPropertyChanging("Fee");
                _Fee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fee");
                OnFeeChanged();
            }
        }
        private global::System.Int32 _Fee;
        partial void OnFeeChanging(global::System.Int32 value);
        partial void OnFeeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KCDC2012Model", Name="Session")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Session : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Session object.
        /// </summary>
        /// <param name="sessionID">Initial value of the SessionID property.</param>
        public static Session CreateSession(global::System.Int32 sessionID)
        {
            Session session = new Session();
            session.SessionID = sessionID;
            return session;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SessionID
        {
            get
            {
                return _SessionID;
            }
            set
            {
                if (_SessionID != value)
                {
                    OnSessionIDChanging(value);
                    ReportPropertyChanging("SessionID");
                    _SessionID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SessionID");
                    OnSessionIDChanged();
                }
            }
        }
        private global::System.Int32 _SessionID;
        partial void OnSessionIDChanging(global::System.Int32 value);
        partial void OnSessionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Approved
        {
            get
            {
                return _Approved;
            }
            set
            {
                OnApprovedChanging(value);
                ReportPropertyChanging("Approved");
                _Approved = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Approved");
                OnApprovedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Approved;
        partial void OnApprovedChanging(Nullable<global::System.Boolean> value);
        partial void OnApprovedChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KCDC2012Model", Name="Speaker")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Speaker : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Speaker object.
        /// </summary>
        /// <param name="speakerID">Initial value of the SpeakerID property.</param>
        public static Speaker CreateSpeaker(global::System.Int32 speakerID)
        {
            Speaker speaker = new Speaker();
            speaker.SpeakerID = speakerID;
            return speaker;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SpeakerID
        {
            get
            {
                return _SpeakerID;
            }
            set
            {
                if (_SpeakerID != value)
                {
                    OnSpeakerIDChanging(value);
                    ReportPropertyChanging("SpeakerID");
                    _SpeakerID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SpeakerID");
                    OnSpeakerIDChanged();
                }
            }
        }
        private global::System.Int32 _SpeakerID;
        partial void OnSpeakerIDChanging(global::System.Int32 value);
        partial void OnSpeakerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateOfBirth
        {
            get
            {
                return _DateOfBirth;
            }
            set
            {
                OnDateOfBirthChanging(value);
                ReportPropertyChanging("DateOfBirth");
                _DateOfBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfBirth");
                OnDateOfBirthChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateOfBirth;
        partial void OnDateOfBirthChanging(Nullable<global::System.DateTime> value);
        partial void OnDateOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> YearsExperience
        {
            get
            {
                return _YearsExperience;
            }
            set
            {
                OnYearsExperienceChanging(value);
                ReportPropertyChanging("YearsExperience");
                _YearsExperience = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("YearsExperience");
                OnYearsExperienceChanged();
            }
        }
        private Nullable<global::System.Int32> _YearsExperience;
        partial void OnYearsExperienceChanging(Nullable<global::System.Int32> value);
        partial void OnYearsExperienceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> HasBeard
        {
            get
            {
                return _HasBeard;
            }
            set
            {
                OnHasBeardChanging(value);
                ReportPropertyChanging("HasBeard");
                _HasBeard = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HasBeard");
                OnHasBeardChanged();
            }
        }
        private Nullable<global::System.Boolean> _HasBeard;
        partial void OnHasBeardChanging(Nullable<global::System.Boolean> value);
        partial void OnHasBeardChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BlogURL
        {
            get
            {
                return _BlogURL;
            }
            set
            {
                OnBlogURLChanging(value);
                ReportPropertyChanging("BlogURL");
                _BlogURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BlogURL");
                OnBlogURLChanged();
            }
        }
        private global::System.String _BlogURL;
        partial void OnBlogURLChanging(global::System.String value);
        partial void OnBlogURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Employer
        {
            get
            {
                return _Employer;
            }
            set
            {
                OnEmployerChanging(value);
                ReportPropertyChanging("Employer");
                _Employer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Employer");
                OnEmployerChanged();
            }
        }
        private global::System.String _Employer;
        partial void OnEmployerChanging(global::System.String value);
        partial void OnEmployerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RegistrationDate
        {
            get
            {
                return _RegistrationDate;
            }
            set
            {
                OnRegistrationDateChanging(value);
                ReportPropertyChanging("RegistrationDate");
                _RegistrationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RegistrationDate");
                OnRegistrationDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _RegistrationDate;
        partial void OnRegistrationDateChanging(Nullable<global::System.DateTime> value);
        partial void OnRegistrationDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KCDC2012Model", Name="Technology")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Technology : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Technology object.
        /// </summary>
        /// <param name="technologyID">Initial value of the TechnologyID property.</param>
        public static Technology CreateTechnology(global::System.Int32 technologyID)
        {
            Technology technology = new Technology();
            technology.TechnologyID = technologyID;
            return technology;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TechnologyID
        {
            get
            {
                return _TechnologyID;
            }
            set
            {
                if (_TechnologyID != value)
                {
                    OnTechnologyIDChanging(value);
                    ReportPropertyChanging("TechnologyID");
                    _TechnologyID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TechnologyID");
                    OnTechnologyIDChanged();
                }
            }
        }
        private global::System.Int32 _TechnologyID;
        partial void OnTechnologyIDChanging(global::System.Int32 value);
        partial void OnTechnologyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Technology1
        {
            get
            {
                return _Technology1;
            }
            set
            {
                OnTechnology1Changing(value);
                ReportPropertyChanging("Technology1");
                _Technology1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Technology1");
                OnTechnology1Changed();
            }
        }
        private global::System.String _Technology1;
        partial void OnTechnology1Changing(global::System.String value);
        partial void OnTechnology1Changed();

        #endregion
    
    }

    #endregion
    
}
